lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
plugins:
  - jekyll-target-blank
  - jekyll-remote-theme
theme: jekyll-theme-cayman
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge