name: Initiative Request - Auto Comment

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  add-comment:
    if: contains(github.event.issue.labels.*.name, 'new-initiative-request')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt-get install -y jq
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run GPT script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          output=$(python scripts/gpt_script.py)
          echo "Raw output: $output"
          processed_output=$(echo "$output" | jq -c .)
          echo "RESPONSE=$processed_output" >> $GITHUB_ENV

      - name: Post comment
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.issue.number;
            const responseJSON = JSON.parse(process.env.RESPONSE);
            const response = "```json\n" + JSON.stringify(responseJSON, null, 2) + "\n```";
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: response
            });
